### ISSUE TITLE
Custom authentication bundle for Symfony 4 and EU Login

### ISSUE THREAD

**Issue by drupol** [eufossa/eu-hackathon-2019#1]
**Project name**
EC PHP - Custom authentication bundle for Symfony 4 and EU Login

**Project website**
EU Login authentication platform: https://webgate.ec.europa.eu/cas/about.html

**Project repository**
None yet

**Challenge description**
Working on a custom Symfony flex bundle that let people authenticate against the European Commission login platform [EU Login](https://webgate.ec.europa.eu/cas/about.html).
2 protocols can/should be used: CAS or/and OpenId Connect.

**Link(s) to existing issues**
None yet

**Comment by jfhovinne** [comment]
Closing, see achievements/ecphp.md.
