### ISSUE TITLE
midPoint

### ISSUE THREAD

**Issue by igor-farinic** [eufossa/eu-hackathon-2019#10]
midPoint

https://wiki.evolveum.com

https://github.com/Evolveum/midpoint

**Challenge description**

1.  Stories of midPoint
	•	Customer success/failure stories you would like to share
	•	Best practices you have adopted for midPoint projects
	•	Main drivers to go for midPoint 
2. midPoint CLI – community contributed
	•	Discussion about acceptance of the CLI contribution, hands-on experience with the author, possibilities to bundle with midPoint
3. End-to-end testing
	•	Community discussions, approach, lessons learned => update design and approach and implementation to the end-to-end testing
4. Authorization / SSO / 2FA / credentials management
	•	Community design session to take MFA integrations with midPoint to the next level
5. Connectors, development, maintenance, support
	•	Community discussion and approach to resolve the situations and issues around connectors (implementation, testing, automated testing environments, maintenance, responsibilities)
6. Deployment best practices
	•	Lessons learned from deployment projects with midpoint and life with midPoint from community. Compilation of proposals to speed-up the deployment projects, hints and tricks to get it done faster, feature gaps for optimized midPoint deployment;
	•	Git versioning of configuration – how to version and automate deployment of configuration to avoid problems like OIDs changing between Dev, Stage and Prod on objects like roles. How to solve a new connector version needs changes in multiple files. 
7. Reporting
	•	Lessons learned by community. Static vs live reporting, preference and approach.
	•	Find a future way to reporting to avoid limitation and legacy of Jasper reporting. 
8. Governance and compliance
	•	Collecting use-cases from community for the governance and compliance functionality
9. midPoint studio
	•	Future and approach to the community eclipse based plugins for midPoint configuration. Next generation of the midpoint IDE and a course set to midPoint studio
10. Documentation 
	•	Community discussion how to keep documentation up-to-date, cleanups and community contributions. 
11. midPoint  in HigherEd 
	•	open discussion about higher education needs to tailor midPoint for Universities, Colleges, Scientific institutions, …
12. midPoint operations & maintenance
	•	midPoint best practices in production, operation of midPoint, monitoring, diagnostics. 
13. midPoint performance
	•	Future of midPoint in large deployments, approach, maintainability, technical integration architecture, bulk changes

**Link(s) to existing issue(s)**

**Comment by igor-farinic** [comment]
14. Roadmap
15. Workflows

**Comment by petergietz** [comment]
16. subscription policy

**Comment by khazelton** [comment]
Bullets on 11) midPoint in higher education: http://j.mp/mPhigherEd

**Comment by igor-farinic** [comment]
midpoint-cli source code: https://gitlab.com/alcibiade/midpoint-cli

**Comment by igor-farinic** [comment]
End-to-end testing notes:
- Schrodinger - community votes to make it done. It is done, just minimalistic (https://github.com/Evolveum/midpoint/tree/master/tools/schrodinger);
- Comparator tool - midCredible (https://github.com/Evolveum/midcredible). Tool to compare data provisioned by midPoint and existing state; works for DBs and LDAP/ADs.

**Comment by tom-jordan23** [comment]
For midPoint in Higher Education discussion - **Capability map for identity in higher eduction (University of Wisconsin)** - https://drive.google.com/a/wisc.edu/file/d/1VejY_zbZyMbxgv4I5A8Rko3G-WxQg1Ft/view?usp=sharing

**Comment by igor-farinic** [comment]
Community public discussion channel: https://gitter.im/Evolveum/midpoint

**Comment by igor-farinic** [comment]
Help in operations: Customizable Dashboards: 
https://wiki.evolveum.com/display/midPoint/Customizable+Dashboards
https://wiki.evolveum.com/display/midPoint/Dashboards%2C+Widgets+and+Reports+Design+Notes

**Comment by igor-farinic** [comment]
Source systems thresholds, but be aware of limitations for now, no multithreads, no multinode support:
https://wiki.evolveum.com/display/midPoint/Thresholds

**Comment by markussteiner** [comment]
Hi All
still on the way back home and still with a smile on my face. It was a great event, very interesting discussions and a big pleasure to meat you all.

Looking forward for a next event!
regards, Markus

**Comment by davidandrewcope** [comment]
Hello. It was great meeting you all at the event and hope we can do it again in the future!

One question, in going over my notes, I remember a discussion about using the 'comparator' tool. Can someone point me to the wiki page for that, if there is one?

**Comment by igor-farinic** [comment]
> Hello. It was great meeting you all at the event and hope we can do it again in the future!
> 
> One question, in going over my notes, I remember a discussion about using the 'comparator' tool. Can someone point me to the wiki page for that, if there is one?

Comparator tool - midCredible (https://github.com/Evolveum/midcredible). Tool to compare data provisioned by midPoint and existing state; works for DBs and LDAP/ADs.

**Comment by davidandrewcope** [comment]
> > Hello. It was great meeting you all at the event and hope we can do it again in the future!
> > One question, in going over my notes, I remember a discussion about using the 'comparator' tool. Can someone point me to the wiki page for that, if there is one?
> 
> Comparator tool - midCredible (https://github.com/Evolveum/midcredible). Tool to compare data provisioned by midPoint and existing state; works for DBs and LDAP/ADs.

Perfect! Thank you!
