### ISSUE TITLE
FLUX TL

### ISSUE THREAD

**Issue by duband** [eufossa/eu-hackathon-2019#11]
**FLUX TL**

**Project website**
TBA
**Project repository**
Internal. Not yet open-sourced (open source planned for the near future).

**Challenge description**

Brainstorm and discuss ideas for improvements and the evolution of FLUX TL.

-  Move FluxTL to the cloud:

    - Flux is composed of three modules : Flux (sending service), FluxWS (receiving service),  and Bridge (interface to internal applications). We can move Flux, and FluxWS to the cloud.

    - we can send a reference in the payload instead of sending the whole message. The whole message will be persisted on the cloud.  It will render transmission efficient

     - save the payload temporarily only once until timeout  has elapsed to reduce duplication

- Simplify the FLUX node configuration : 

    - develop a user interface
    - simplify configuration; execute sanity verification checks on current configuration.

- optimize protocol

- improved message delivery confirmation

- decouple components

**Link(s) to existing issue(s)**

**Comment by jfhovinne** [comment]
Closing, see #18
