### ISSUE TITLE
PHPUnit: refactor internals for large-scale automation

### ISSUE THREAD

**Issue by epdenouden** [eufossa/eu-hackathon-2019#12]
**PHPUnit, the unit testing framework for PHP**
Project website: https://phpunit.de/
Repository: https://github.com/sebastianbergmann/phpunit/

**Challenge description**
Development of PHP applications has changed a lot as frameworks and infrastructure matures. Applications and test collections have grown and continuous integration is mostly done on rented on-demand infrastructure.

As a result developer behaviour has shifted towards more of a "let the pipeline and auto-scalers sort it out", often resulting in very slow test collections that are only usable because of third party hosted pipelines like GitHub/Gitlab/Travis.

**Related issues**
- Working draft for Event subsystem: https://github.com/sebastianbergmann/phpunit/issues/3390 with a first pull https://github.com/theseer/phpunit/pull/1
- Extend dependency checker: https://github.com/sebastianbergmann/phpunit/issues/3519
- Refactor data providers: https://github.com/sebastianbergmann/phpunit/issues/3736

**Comment by jfhovinne** [comment]
Closing, see #19
