### ISSUE TITLE
"Let us start the conversation"

### ISSUE THREAD

**Issue by spriebsch** [eufossa/eu-hackathon-2019#17]
Documentation of discussion about OSS on Sunday afternoon

![oss](https://user-images.githubusercontent.com/61342/66270412-961e2b80-e853-11e9-9eb0-65b6d9554059.jpg)

We will follow up with a blog post.

**Comment by epdenouden** [comment]
@sebastianbergmann has already published the keynote that kicked off this conversation:
- [slides](https://thephp.cc/dates/2019/10/eu-fossa-2/may-the-source-be-with-eu)
- [Twitter thread](https://twitter.com/s_bergmann/status/1180801252957011968?s=20)

Quick transcription of the stickies. As I didn't take accurate meeting minutes during the freeform discussion, I didn't catch all names. Please put any corrections and additions in the comments and I'll update this one.

Jean-François Hovinne @jfhovinne
- free support requested
- passed the baton
- we should/could sell the software
- free as in beer vs freedom
- impacted family life

Radovan Semancik @semancik from midPoint
- founded small company
- commercial support to raise prio of bug report
- informal standard, free vs commercial
- we always fix security issues, whoever requests them
- 3-4 years until company is viable
- hard to sell services 'free beer' expectation 
- once free, always free [....]
- it is knowledge sharing
- our product was too complex to steal

Stefan Priebsch @spriebsch
- OSS developers are not good at marketing
- [complaint from corporate:] "we cannot use OSS when there is no commercial support"

API-platform: _please add your name in the comments_
- we open-sourced our proprietary platform
- OSS are building blocks for solutions that we sell
- OSS is free marketing

unattributed:
- more money is spent on [...] than OSS
- if you want our time, then pay us
- value of implementation vs value of software
- OSS is not a business model, services are
- OSS enables us to sell services

**Comment by jfhovinne** [comment]
@spriebsch @epdenouden
See [achievements/conversation.md](https://github.com/eufossa/eu-hackathon-2019/blob/master/achievements/conversation.md). PRs welcome.

**Comment by jfhovinne** [comment]
Closing.
