### ISSUE TITLE
DSS

### ISSUE THREAD

**Issue by pvandenbroucke** [eufossa/eu-hackathon-2019#5]
**DSS : Digital Signature Services**

**https://ec.europa.eu/cefdigital/wiki/display/CEFDIGITAL/DSS**

**https://github.com/esig/dss**

**Challenge description**

1. Improve the security

Constant evolution
XSW, XXE, injections, MITM,…
Vulnerabilities in the code
Vulnerabilities in dependencies
Misconfiguration / Misusage

2. Improve the performance

Not easy to test / reproduce (reduce external resource usages, control on the complete test environment http://dss.nowina.lu/pki-factory/, same machine / memory / JVM / …)
Cache vs stateless objects
VisualVM : https://visualvm.github.io/

3. Improve the PDF part

Common code
2 implementations (PDFBox / OpenPDF)
Similar features
Some differences
Visible signatures

4. Improve Java 12 support

DSS 5.5 : Framework compiled with Java 12 + Demonstrations compiled with Java 8
Package/module re-organization 
Main reflections have been replaced with ServiceLoader
Multi-Release jar is used in dss-token (changes in SunPKCS11)

Met issues 
- Smartcard.io -> MOCCA ([DSS-1728](https://ec.europa.eu/cefdigital/tracker/browse/DSS-1728))
- Commons-IO / PDFBox don’t support JPMS (dss-utils-google-guava / dss-pades-openpdf can be used in replacement)

5. Improve the standalone application (Java FX)

Provided standalone application
Work in offline mode
Very limited features 
No TL / LOTL loading (will be integrated in future)
Only baseline-profile B or T
Requires Oracle Java 8
Splitted Java FX : https://openjfx.io/
Embed signature validation
User-friendly configuration ?
Executable application ?

6. Open discussion

Feel free to propose any other suggestions / points.

**Useful links :** 

- Portal : https://ec.europa.eu/cefdigital/wiki/display/CEFDIGITAL/eSignature
- FAQ : https://ec.europa.eu/cefdigital/wiki/display/CEFDIGITAL/eSignature+FAQ
- Demonstration : https://ec.europa.eu/cefdigital/DSS/webapp-demo
- Documentation : https://ec.europa.eu/cefdigital/DSS/webapp-demo/doc/dss-documentation.html

- Bitbucket : https://ec.europa.eu/cefdigital/code/projects/ESIG
- GitHub : https://github.com/esig/
- Jira : https://ec.europa.eu/cefdigital/tracker/projects/DSS/
- Quality : https://sonarcloud.io/dashboard?id=eu.europa.ec.joinup.sd-dss%3Asd-dss
- Nexus : https://ec.europa.eu/cefdigital/artifact/

**Comment by pvandenbroucke** [comment]
Here are the created tickets after the brainstorming sessions : 

- [DSS-1816](https://ec.europa.eu/cefdigital/tracker/browse/DSS-1816) : EU-Hackathon 2019: Timestamp only validation
- [DSS-1817](https://ec.europa.eu/cefdigital/tracker/browse/DSS-1817) : EU-Hackathon 2019: Include schema version to validation reports
- [DSS-1818](https://ec.europa.eu/cefdigital/tracker/browse/DSS-1818) : EU-Hackathon 2019: Custom validation policy must be applied on top of the default policy
- [DSS-1819](https://ec.europa.eu/cefdigital/tracker/browse/DSS-1819) : EU-Hackathon 2019: Review exceptions
- [DSS-1820](https://ec.europa.eu/cefdigital/tracker/browse/DSS-1820) : EU-Hackathon 2019: Timestamp qualification verification
- [DSS-1821](https://ec.europa.eu/cefdigital/tracker/browse/DSS-1821) : EU-Hackathon 2019: Use WeakHashMap for efficient memory clean
- [DSS-1822](https://ec.europa.eu/cefdigital/tracker/browse/DSS-1822) : EU-Hackathon 2019: PDF/A validation
- [DSS-1823](https://ec.europa.eu/cefdigital/tracker/browse/DSS-1823) : EU-Hackathon 2019: Multiple Offline CRL/OCSP sources

Thanks to all participants and organizers !

**Comment by jfhovinne** [comment]
Closing, see #20
